apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
  template:
    metadata:
      labels:
        app: geoserver
    spec:
      containers:
        - name: geoserver
          image: docker.io/geoserver/geoserver:2.23.2
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/geoserver/data_dir
              name: geoserver-data
      volumes:
        - name: geoserver-data
          persistentVolumeClaim:
            claimName: geoserver-data
